FROM python:3

ENV ANSIBLE_HOST_KEY_CHECKING=False

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        sshpass \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | apt-key add - \
    && add-apt-repository \
           "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
           $(lsb_release -cs) \
           stable" \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
        docker-ce \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /ansible-supergiant
ADD tests/runner-requirements.txt tests/runner-requirements.txt
RUN pip --disable-pip-version-check install -r tests/runner-requirements.txt
ADD . .

WORKDIR /ansible-supergiant/tests
CMD ["ansible-playbook", "-i", "inventory.ini", "test.yml"]
