---

- name: create name for build image
  set_fact:
    build_image_name: "supergiant-build-{{ 999999 | random | to_uuid }}"

- block:
    - name: create temporary build directory
      delegate_to: localhost
      tempfile:
        state: directory
        suffix: build
      register: build_directory

    - name: clone Supergiant repository
      git:
        repo: "{{ supergiant_git_repository }}"
        dest: "{{ build_directory }}"
        recursive: yes
        clone: yes
        version: "{{ supergiant_version }}"

    - name: build Supergiant in Docker
      delegate_to: localhost
      become: yes
      docker_image:
        name: "{{ build_image_name }}"
        path: .
        dockerfile: "{{ build_directory }}/build/Dockerfile.build"

  always:
    - name: delete build image
      delegate_to: localhost
      become: yes
      docker_image:
        name: "{{ build_image_name }}"
        state: absent

    - name: remove build directory
      delegate_to: localhost
      file:
        path: "{{ build_directory }}"
        state: absent
  delegate_to: localhost
