---

- name: create name for build image
  set_fact:
    build_image_name: "supergiant-build-{{ 999999 | random | to_uuid }}"

- block:
    - name: create temporary build directory
      delegate_to: localhost
      tempfile:
        state: directory
        suffix: build
        path: "{{ supergiant_docker_build_temp_directory }}"
      register: build_directory

    - name: clone Supergiant repository
      delegate_to: localhost
      git:
        repo: "{{ supergiant_git_repository }}"
        dest: "{{ build_directory.path }}"
        recursive: yes
        clone: yes
        version: "{{ supergiant_version }}"

    - name: build Supergiant in Docker
      delegate_to: localhost
      become: yes
      docker_image:
        name: "{{ build_image_name }}"
        path: "{{ build_directory.path }}"
        dockerfile: "{{ role_path }}/files/Dockerfile"

    - name: create instance with built Supergiant binary
      delegate_to: localhost
      become: yes
      docker_container:
        name: "{{ build_image_name }}-instance"
        image: "{{ build_image_name }}"
        command: sh

    - name: copy Supergiant binary from builder instance
      delegate_to: localhost
      become: yes
      shell: "docker cp {{ build_image_name }}-instance:/go/src/github.com/supergiant/supergiant/dist/bin/supergiant {{ build_directory.path }}"

    - name: install built binary on remote
      become: yes
      copy:
        src: "{{ build_directory.path }}/supergiant"
        dest: "{{ supergiant_server_install_location }}"
        mode: 0770

  always:
    - name: delete build container
      delegate_to: localhost
      become: yes
      docker_container:
        name: "{{ build_image_name }}-instance"
        state: absent

    - name: delete build image
      delegate_to: localhost
      become: yes
      docker_image:
        name: "{{ build_image_name }}"
        state: absent

    - name: remove build directory
      delegate_to: localhost
      become: yes
      file:
        path: "{{ build_directory }}"
        state: absent
